In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\anshuman\Desktop\Mobile Price Prediction\data\train.csv")
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [3]:
df.drop("price_range",axis=1)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7   
1       0.7        136        3   6        905      1988  2631    17     3   
2       0.9        145        5   6       1263      1716  2603    11     2   
3       0.8        131        6   9       1216      1786  2769    16     8   
4       0.6        141        2  14       1208      1212  1411     8     2   
...     ...        ...      ...  ..        ...       ...   ...   ...   ...   
1995    0.8        106        6  14       1222      1890   668    13     4   
1996    0.2        187        4   3        915      1965  2032    11    10   
1997    0.7        108        8   3        868      1632  3057     9     1   
1998    0.1        145        5   5        336       670   869    18    10   
1999    0.9        168        6  16        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  
0            19        0             0     1  
1             7        1             1     0  
2             9        1             1     0  
3            11        1             0     0  
4            15        1             1     0  
...         ...      ...           ...   ...  
1995         19        1             1     0  
1996         16        1             1     1  
1997          5        1             1     0  
1998         19        1             1     1  
1999          2        1             1     1  

[2000 rows x 20 columns]

In [108]:
import pickle
import pandas as pd

with open(r"C:\Users\anshuman\Desktop\Mobile Price Prediction\artifacts\model.pkl","rb") as f:
    model = pickle.load(f)
with open(r"C:\Users\anshuman\Desktop\Mobile Price Prediction\artifacts\preprocessor.pkl","rb") as f:
    preprocessor = pickle.load(f)
# model.predict()

In [71]:
class CustomData:
    def __init__(self, battery_power, blue, clock_speed, dual_sim, fc, four_g, int_memory, m_dep, mobile_wt, n_cores, pc, px_height, px_width, ram, sc_h, sc_w, talk_time, three_g, touch_screen, wifi):
        self.battery_power = battery_power
        self.blue = blue
        self.clock_speed = clock_speed
        self.dual_sim = dual_sim
        self.fc = fc
        self.four_g = four_g
        self.int_memory = int_memory
        self.m_dep = m_dep
        self.mobile_wt = mobile_wt
        self.n_cores = n_cores
        self.pc = pc
        self.px_height = px_height
        self.px_width = px_width
        self.ram = ram
        self.sc_h = sc_h
        self.sc_w = sc_w
        self.talk_time = talk_time
        self.three_g = three_g
        self.touch_screen = touch_screen
        self.wifi = wifi
    
    def get_data_as_dataframe(self):
        data = {
            'battery_power': [self.battery_power],
            'blue': [self.blue],
            'clock_speed': [self.clock_speed],
            'dual_sim': [self.dual_sim],
            'fc': [self.fc],
            'four_g': [self.four_g],
            'int_memory': [self.int_memory],
            'm_dep': [self.m_dep],
            'mobile_wt': [self.mobile_wt],
            'n_cores': [self.n_cores],
            'pc': [self.pc],
            'px_height': [self.px_height],
            'px_width': [self.px_width],
            'ram': [self.ram],
            'sc_h': [self.sc_h],
            'sc_w': [self.sc_w],
            'talk_time': [self.talk_time],
            'three_g': [self.three_g],
            'touch_screen': [self.touch_screen],
            'wifi': [self.wifi],}
        return pd.DataFrame(data)
    

In [123]:
# import numpy as np

# validity_test = np.array([[858,0,2.2,0,1,0,50,0.1,84,1,2,528,1416,3978,17,16,3,1,1,0],
# [794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0],
# [1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1],
# [1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0,],
# [1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1,],
# [510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1]])
validity_real = [3,0,2,3,0,3]
df = CustomData(510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1)
df = df.get_data_as_dataframe()

In [124]:
df = preprocessor.transform(df)

In [125]:
model.predict(df)

array([3], dtype=int64)

In [75]:
data = pd.read_csv(r"C:\Users\anshuman\Desktop\Mobile Price Prediction\data\data.csv")
data_ = data.drop("price_range",axis=1)
data_

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7   
1       0.7        136        3   6        905      1988  2631    17     3   
2       0.9        145        5   6       1263      1716  2603    11     2   
3       0.8        131        6   9       1216      1786  2769    16     8   
4       0.6        141        2  14       1208      1212  1411     8     2   
...     ...        ...      ...  ..        ...       ...   ...   ...   ...   
1995    0.8        106        6  14       1222      1890   668    13     4   
1996    0.2        187        4   3        915      1965  2032    11    10   
1997    0.7        108        8   3        868      1632  3057     9     1   
1998    0.1        145        5   5        336       670   869    18    10   
1999    0.9        168        6  16        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  
0            19        0             0     1  
1             7        1             1     0  
2             9        1             1     0  
3            11        1             0     0  
4            15        1             1     0  
...         ...      ...           ...   ...  
1995         19        1             1     0  
1996         16        1             1     1  
1997          5        1             1     0  
1998         19        1             1     1  
1999          2        1             1     1  

[2000 rows x 20 columns]

In [76]:
y_pred = model.predict(data_)

c:\Users\anshuman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [77]:
y_pred

array([3, 3, 3, ..., 3, 3, 3], dtype=int64)

In [48]:
from sklearn.metrics import r2_score

In [55]:
y_true = data["price_range"]
r2_score(y_true,y_pred)

-1.7999999999999998

In [91]:
from sklearn.linear_model import  LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import  StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.ensemble import RandomForestRegressor
import sys

sys.path.append(r"C:\Users\anshuman\Desktop\Mobile Price Prediction\src")
from utilities.ModelTrainer import  model_trainer
models = {
            "Linear Regression": LinearRegression(),
            "Logistic Regression": LogisticRegression(),
            "KNeighborsRegressor": KNeighborsRegressor(),
            "SVC": SVC(),
            "DecisionTreeClassifier": DecisionTreeClassifier(),
            "XGBRegressor": XGBRegressor(),
            "CatBoostRegressor": CatBoostRegressor(),
            "RandomForestRegressor": RandomForestRegressor(),
        }

df = pd.read_csv(r"C:\Users\anshuman\Desktop\Mobile Price Prediction\data\data.csv")

X = df.drop("price_range", axis=1)
scaler = StandardScaler()
X_transformed = scaler.fit_transform(X)
y = df["price_range"]

X_train, X_test, y_train, y_test = train_test_split(X_transformed,y ,test_size=0.33, random_state=42)

model,score = model_trainer(models,X_train, y_train, X_test,y_test)

Learning rate set to 0.042881
0:	learn: 1.0795819	total: 2.39ms	remaining: 2.39s
1:	learn: 1.0433908	total: 4.42ms	remaining: 2.21s
2:	learn: 1.0093971	total: 6.35ms	remaining: 2.11s
3:	learn: 0.9767662	total: 8.1ms	remaining: 2.02s
4:	learn: 0.9503356	total: 10.1ms	remaining: 2.01s
5:	learn: 0.9192634	total: 12.1ms	remaining: 2s
6:	learn: 0.8881639	total: 14.1ms	remaining: 2s
7:	learn: 0.8605529	total: 16ms	remaining: 1.98s
8:	learn: 0.8335352	total: 18.1ms	remaining: 2s
9:	learn: 0.8070090	total: 20.1ms	remaining: 1.99s
10:	learn: 0.7805874	total: 22.1ms	remaining: 1.98s
11:	learn: 0.7581270	total: 24.2ms	remaining: 1.99s
12:	learn: 0.7379082	total: 26ms	remaining: 1.98s
13:	learn: 0.7152845	total: 27.8ms	remaining: 1.96s
14:	learn: 0.6949711	total: 29.9ms	remaining: 1.96s
15:	learn: 0.6764276	total: 32ms	remaining: 1.97s
16:	learn: 0.6591029	total: 34ms	remaining: 1.97s
17:	learn: 0.6434664	total: 35.9ms	remaining: 1.96s
18:	learn: 0.6256248	total: 38ms	remaining: 1.96s
19:	learn: 0

In [92]:
model

LogisticRegression()

In [93]:
y_pred = model.predict(X_test)

In [94]:
r2_score(y_test,y_pred)

0.9677414099284771

In [96]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [97]:
y_pred = model.predict(X_test)

In [98]:
r2_score(y_test,y_pred)

0.9677414099284771

In [99]:
df = CustomData(1815,0,2.8,0,2,0,33,0.6,159,4,17,607,748,1482,18,0,2,1,0,0)
df = df.get_data_as_dataframe()

In [101]:
df = scaler.transform(df)
model.predict(df)

array([1], dtype=int64)